### ISSUE TITLE
Docker machine is not present on the image for the last build (07/02/2022)

### ISSUE THREAD

**Issue by FJEANNOT** [OpenDroneMap/ClusterODM#91] opened 2022-02-07 18:56 UTC
### What is the problem?

On the last build there is a XML file instead of the docker-machine binary:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>9X64YXJWB3NTJXDY</RequestId><HostId>gcYPM2y5ZRki30XSL44791CDe8Nz0kMvQu0PYlmKNUXVMFzebFBYkjlAB8pfiG3WqQ6uygHt1wc=</HostId></Error>
```
So the autoscaler is not working anymore.

### How can we reproduce this?

Just pull the latest image and try to run a `docker-machine` command

**Comment by pierotofy** [comment] 2022-02-07 19:07
Probably a regression due to https://github.com/OpenDroneMap/ClusterODM/commit/1ab2ce760c92a8388e7f75ee21184d4e795d0b7e

**Comment by FJEANNOT** [comment] 2022-02-07 19:18
Could you push an older version of the image for now? They are not versionned in docker-hub

**Comment by pierotofy** [comment] 2022-02-07 23:41
Should be fixed with https://github.com/OpenDroneMap/ClusterODM/commit/311dbb05d275b2ebc0b869295bfa7b9b700aec75 thanks for the report! Feel free to re-open if the issue persists :pray:

**Closed by pierotofy** 2022-02-07 23:41 UTC
Labels: software fault, help wanted
