### ISSUE TITLE
Cluster node seems to be offline: HTTPConnectionPool(host='127.0.0.1', port=3001)

### ISSUE THREAD

**Issue by ChipwizBen** [OpenDroneMap/ClusterODM#29] opened 2019-07-23 06:44 UTC
There's a weird intermittent connectivity issue for the cluster software:

`[ERROR]   Cluster node seems to be offline: HTTPConnectionPool(host='127.0.0.1', port=3001): Max retries exceeded with url: /info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9861261810>: Failed to establish a new connection: [Errno 111] Connection refused',))`

It works about 50% of the time, but times out for the rest. ClusterODM is started via systemd and remains running fine:

`ExecStart=/usr/bin/node /opt/ClusterODM/index.js -p 3001`

When submitting a job, it almost seems like WebODM is trying to brute force a job into ClusterODM, as the number of connections is huge:
```
root@survey-dev:~# netstat -tapn | grep 3001 | wc -l
269
```

```
tcp        0      0 127.0.0.1:43016         127.0.0.1:3001          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42818         127.0.0.1:3001          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42802         127.0.0.1:3001          TIME_WAIT   -               
tcp6       0      0 :::3001                 :::*                    LISTEN      13085/node      
tcp6       0      0 127.0.0.1:3001          127.0.0.1:43050         TIME_WAIT   - 
```

telneting to the port works fine. Server load is very low. Packet loss is zero (it's localhost).

**Comment by pierotofy** [comment] 2019-07-23 12:28
Note that WebODM does parallel uploads, so makes multiple connections to ClusterODM. Not sure if that's related.

**Comment by ChipwizBen** [comment] 2019-07-24 08:20
I find that keeping the default port 3000 is more reliable, oddly. Perhaps some hard-coded 3000 lingering somewhere?

**Comment by pierotofy** [comment] 2019-07-24 14:03
Mm, not that I'm aware (ports should be configurable).

**Comment by pierotofy** [comment] 2020-04-03 23:36
Closing due to inability to reproduce.

**Closed by pierotofy** 2020-04-03 23:36 UTC
Labels: help wanted, possible software fault
